theme: jekyll-theme-minimal
title: Q1ngX1's homepage
description: Study notes
kramdown:
  parse_block_html: true
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      disable: true

# 排除不需要 Jekyll 处理的文件和目录
exclude:
  - assets/notes/
  - assets/attachements/
  - dist/
  - node_modules/
  - scripts/
